### ISSUE TITLE
Integration into an already running server

### ISSUE THREAD

**Issue by xzAtlas** [ObjectManagerManager/SMAPIDedicatedServerMod#12]
Hi i hope this is the place to post this I have an already running server I host with a friend through stardews integrated hosting however I'm heading away for about 2 weeks and I'd like to keep it up for her but most mods I've tried seem to not work unfortunately I'm wondering if maybe there's a way to integrate this onto my already running server if it's possible or if this is only usable for new servers any guidance is appreciated

**Comment by ObjectManagerManager** [comment]
I think that should work just fine, but you should backup your save first to be safe.

Here are the steps: Install SMAPI (if you haven't already). Download the latest build of the mod (the zip file at the top level of this repository) and extract the folder from inside it. Drop that folder into your SMAPI Mods folder. I just updated the build to match the latest source code, so it should be good to go. When you run the game with the mod installed for the first time, it'll generate a _new_ farm called "Stardew" by default. After that, close the game, navigate to the mod folder, and edit the config file. Change the name of the farm specified in the config file to the name of your farm (along with other configuration details). The name must be exact (case sensitive, punctuation sensitive, etc). Next time you run the game, it should open _your_ farm.

Your character (the host) will become automated, doing very little besides what's absolutely required for progression. There may still be some missing features regarding story progression (this mod is still not well tested), so your friend might not be able to progress in the storyline, depending on how far along your farm is.

Let me know if you run into any issues in this process.

**Comment by ObjectManagerManager** [comment]
Oh, and one issue that I hadn't considered is the crop saver. It only works on newly planted crops. Any preexisting crops at installation time will not be recognized as player-planted, so it won't affect them. In addition, when you want to uninstall the mod later, it won't be able to "undo" all of its effects on the saved crops. Of course, once those crops are harvested, it should be a non-issue.
