### ISSUE TITLE
No Friend code / Can't connect to host

### ISSUE THREAD

**Issue by MoritzT** [ObjectManagerManager/SMAPIDedicatedServerMod#13]
Great mod!
I started the host and the game is running, but how can I join the host game?
The host is on a different computer and I can't see a way to join that game.

**Comment by ObjectManagerManager** [comment]
I recommend joining by IP. That's probably the easiest way to go, anyways. (Find the IP address of the host and enter it into the IP address bar when joining over LAN). There might be a way to get it to work over Steam's servers, but I haven't looked into it.

If the host and clients are on the same network, you can join by local IP. You can find your local IP address in various ways depending on your OS (and you can fix it to a static address if you have admin access to the network router). If the host and clients are on different networks, you can port forward and join by global / public IP. You can find your public IP [here](https://www.whatismyip.com/). Note that port forwarding also requires admin access to your network router.

If you don't have admin access to your network router, and the hosts and clients are on different networks, I've heard that you can use something like Hamachi or some sort of proxy, redirecting requests from the proxy server to your local server without port forwarding.

**Comment by MoritzT** [comment]
Switching the host to offline and back to invite-only started to generate invite codes
