### ISSUE TITLE
Attempted Migration to Version 1.6

### ISSUE THREAD

**Issue by Bugsplat123** [ObjectManagerManager/SMAPIDedicatedServerMod#18]
[DedicatedServer(Update).zip](https://github.com/ObjectManagerManager/SMAPIDedicatedServerMod/files/14687121/DedicatedServer.Update.zip)

Hello. I've been using this mod to run a Stardew server for 10+ people and as the 1.6 update came around, the server has broken and the mod no longer worked.
Rather than downgrading back to 1.5.6 I decided to try updating the mod's code to work with 1.6's new framework.
I have updated the mod as best as I can and swapped out deprecated code with the new ones that came with the update. The Solution has been rebuilt successfully with the Net6.0 Framework and the updated NuGet package from PathosChild.

SMAPI will attempt to load the mod when run and fail as of now rather than being skipped due to incompatibility. The issue is currently on line 55 of the StartFarmStage.cs file and line 20 of the HostAutomatorStage.cs file.
With my limited understanding it seem the mod as it is currently written is incapable of creating and loading a save file and is also unable to execute the pause command while no other player is around.

I have removed Crop Saver, Demolish and Build commands as I couldn't figure out how to get them working. 
Event ID's have been converted to string format, along with pet breed selection.
I have also changed the ready check codes as the original code no longer worked. 

Any help on fixing the mod would be greatly appreciated! And I hope my contribution here has helped with the migration should you have been planning to do so as well.

**Comment by Chris82111** [comment]
Hello, the Mod should work with this version [v1.1.0-beta](https://github.com/Chris82111/SMAPIDedicatedServerMod/releases/tag/v1.1.0-beta):

- This version implements additional functions, please check the description in branch [Develop](https://github.com/Chris82111/SMAPIDedicatedServerMod/tree/develop).
- The branch develop and main from the fork cannot be merged, as the merge into this repository (#17) is still open.
